service: crud-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: !Ref ItemsTable
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt ItemsTable.Arn

custom:
  stages:
    - dev
    - prod
  tableName: items-table-${self:provider.stage}

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  createItem:
    handler: src/handlers/createItem.handler
    events:
      - http:
          path: items
          method: post
          cors: true

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          path: items
          method: get
          cors: true

  getItem:
    handler: src/handlers/getItem.handler
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  updateItem:
    handler: src/handlers/updateItem.handler
    events:
      - http:
          path: items/{id}
          method: put
          cors: true

  deleteItem:
    handler: src/handlers/deleteItem.handler
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true

plugins:
  - serverless-plugin-typescript
